on: [push, pull_request]
name: Test
jobs:
  test:
    name: Test ${{ matrix.sketch }} for ${{ matrix.board }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sketch: [LightingNodePRO, SingleStripLightingNodePRO, CommanderPRO, DeviceIDTool, RepeatAndScale, TransformLLFansFormatToStrip, LS100, LightingNodeCORE, NonAddressable, AmbientBacklight]
        board: ["arduino:avr:leonardo", "arduino:avr:micro", "SparkFun:avr:promicro:cpu=16MHzatmega32U4"]
    steps:
    - uses: actions/checkout@master
    - uses: arduino/setup-arduino-cli@v1.0.0
    - name: Install FastLED
      run: arduino-cli lib install FastLED@3.2.0
    - name: Install SparkFun boards
      if: contains(matrix.board, 'SparkFun')
      run: |
        arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/sparkfun/Arduino_Boards/master/IDE_Board_Manager/package_sparkfun_index.json
        arduino-cli core install SparkFun:avr@1.1.5 --additional-urls https://raw.githubusercontent.com/sparkfun/Arduino_Boards/master/IDE_Board_Manager/package_sparkfun_index.json
    - name: Build ${{ matrix.sketch }} for ${{ matrix.board }}
      run: arduino-cli compile --fqbn ${{ matrix.board }} ./examples/${{ matrix.sketch }}
  testUnoMega:
    name: Test UnoMega ${{ matrix.sketch }} for ${{ matrix.board }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sketch: [HoodLoader2UnoMegaController]
        board: ["arduino:avr:uno", "arduino:avr:mega:cpu=atmega2560"]
    steps:
    - uses: actions/checkout@master
    - uses: arduino/setup-arduino-cli@v1.0.0
    - name: Install FastLED
      run: arduino-cli lib install FastLED@3.2.0
    - name: Build ${{ matrix.sketch }} for ${{ matrix.board }}
      run: arduino-cli compile --fqbn ${{ matrix.board }} ./examples/${{ matrix.sketch }}
  test16u2:
    name: Test 16u2 ${{ matrix.sketch }} for ${{ matrix.board }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sketch: [HoodLoader2CLPBridge]
        board: ["HoodLoader2:avr:HoodLoader2atmega16u2:board=uno", "HoodLoader2:avr:HoodLoader2atmega16u2:board=mega2560"]
    steps:
    - uses: actions/checkout@master
    - uses: arduino/setup-arduino-cli@v1.0.0
    - name: Install FastLED
      run: arduino-cli lib install FastLED@3.2.0
    - name: Install HoodLoader2
      run: |
        arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/NicoHood/HoodLoader2/master/package_NicoHood_HoodLoader2_index.json
        arduino-cli core install HoodLoader2:avr@2.0.5 --additional-urls https://raw.githubusercontent.com/NicoHood/HoodLoader2/master/package_NicoHood_HoodLoader2_index.json
    - name: Build ${{ matrix.sketch }} for ${{ matrix.board }}
      run: arduino-cli compile --fqbn ${{ matrix.board }} ./examples/${{ matrix.sketch }}
