on: [push, pull_request]
name: Test
jobs:
  test:
    name: Test ${{ matrix.sketch }} for ${{ matrix.board }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sketch: [LightingNodePRO, SingleStripLightingNodePRO, CommanderPRO, DeviceIDTool]
        board: ["arduino:avr:leonardo", "arduino:avr:micro"]
        include:
        - sketch: HoodLoader2UnoMegaController
          board: "arduino:avr:uno"
          test: 1
        - sketch: HoodLoader2UnoMegaController
          board: "arduino:avr:mega"
          test: 2
    steps:
    - uses: actions/checkout@master
    - name: Install FastLED
      uses: Legion2/download-release-action@v1.0.0
      env:
        TARGET_PATH: libraries
      with:
        args: FastLED/FastLED 3.2.0
    - name: Build ${{ matrix.sketch }} for ${{ matrix.board }}
      uses: Legion2/arduino-builder-action@actions-v2
      with:
        board: ${{ matrix.board }}
        sketchPath: ./examples/${{ matrix.sketch }}/${{ matrix.sketch }}.ino
