on: [push, pull_request]
name: Test
jobs:
  test:
    name: Test sketches
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install FastLED
      uses: Legion2/download-release-action@v1.0.0
      env:
        TARGET_PATH: libraries
      with:
        args: FastLED/FastLED 3.2.0
    - name: Build HoodLoader2UnoMegaController
      uses: Legion2/arduino-builder-action@v1.1.0
      env:
        BOARD_NAME: arduino:avr:uno
        SKETCH_PATH: ./examples/HoodLoader2UnoMegaController/HoodLoader2UnoMegaController.ino
    - name: Build SingleStripLightingNodePRO
      uses: Legion2/arduino-builder-action@v1.1.0
      env:
        BOARD_NAME: arduino:avr:micro
        SKETCH_PATH: ./examples/SingleStripLightingNodePRO/SingleStripLightingNodePRO.ino
    - name: Build CommanderPRO
      uses: Legion2/arduino-builder-action@v1.1.0
      env:
        BOARD_NAME: arduino:avr:leonardo
        SKETCH_PATH: ./examples/CommanderPRO/CommanderPRO.ino
    - name: Build LightingNodePRO
      uses: Legion2/arduino-builder-action@v1.1.0
      env:
        BOARD_NAME: arduino:avr:leonardo
        SKETCH_PATH: ./examples/LightingNodePRO/LightingNodePRO.ino
